version: "3.9"  # optional since v1.27.0
services:

  postgresdb:
    image: postgres
    container_name: postgresdb
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: password
    volumes:
      - ./init-script/postgres:/docker-entrypoint-initdb.d