
spring:
  datasource:
    url: jdbc:postgresql://postgresdb:5432/uni_manager?createDatabaseIfNotExist=true
    username: uni_manager_user
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /api-docs
